// lib/matchIntel.js
// Per-match scouting intel: injuries, form, tactical notes, edge factors
// Updated as of June 13, 2026

export const MATCH_INTEL = {
  mex_sa: {
    result: "2-0",
    homeFlags: ["🏠 Home crowd Mexico City (Azteca)", "⚽ Hirving Lozano fit", "📈 5W in last 6 home WC games"],
    awayFlags: ["😰 First WC since 2010", "🩹 Percy Tau fitness doubt", "📉 Lost last 4 vs CONMEBOL"],
    tacticalNote: "Mexico pressed high and exploited South Africa's high defensive line. Comfortable win.",
    bestBet: "Mexico Win", bestBetOdds: -220, bestBetEdge: 8.2,
    keyEdge: "Mexico dominant at Azteca historically, South Africa limited attacking output in AFCON qualifying",
  },
  kor_cze: {
    result: "2-1",
    homeFlags: ["⚡ Son Heung-min in form (12 EPL goals)", "🏃 High press system under Klinsmann", "📈 Won 4 of last 5"],
    awayFlags: ["🩹 Patrik Schick knee concern", "✈️ Long travel from Europe", "📉 Lost last 3 tournament openers"],
    tacticalNote: "Korea's press disrupted Czech buildup. Son scored twice in second half.",
    bestBet: "Over 2.5 Goals", bestBetOdds: +105, bestBetEdge: 11.4,
    keyEdge: "Both teams press high — high xG game likely. Czech defense vulnerable to pace.",
  },
  can_bih: {
    homeFlags: ["🏠 Home support in Toronto", "⚽ Alphonso Davies fit and starting", "📈 Qualified impressively via CONCACAF"],
    awayFlags: ["✈️ Long travel", "🩹 Edin Džeko (38) — fitness question mark", "😰 First major tournament since 2014"],
    tacticalNote: "Canada conceded early corner goal but equalized through Larin deflection in 78th minute. Result: 1-1.",
    result: "1-1",
    bestBet: "Draw", bestBetOdds: +210, bestBetEdge: 9.1,
    keyEdge: "Alfaro's organized Bosnia block vs Canada's counter-attack speed — draw likely opening game.",
  },
  qat_sui: {
    homeFlags: ["😰 Zero spring prep — 3 friendlies canceled (Middle East conflict)", "📉 Failed to score in 4 of last 5", "🏟️ Domestic-only squad"],
    awayFlags: ["📈 Unbeaten in UEFA qualifying (4W-2D)", "⚽ Granit Xhaka marshaling midfield", "🛡️ Only 2 goals conceded in qualifying"],
    tacticalNote: "Switzerland's defensive solidity and Qatar's attacking impotence creates a lopsided matchup. Swiss should control possession and score early.",
    bestBet: "Switzerland -1.5 AH", bestBetOdds: -115, bestBetEdge: 16.3,
    keyEdge: "Qatar cancelled all spring prep. Cannot score. Swiss defence conceded 2 in 6 qualifying games.",
  },
  bra_mar: {
    homeFlags: ["🩹 Estêvão (hamstring) out", "🩹 Rodrygo out", "🩹 Wesley (RB) out — late tournament injury", "❓ Neymar calf — doubtful", "🆕 Ancelotti first WC game — no competitive baseline"],
    awayFlags: ["🩹 Aguerd (CB) out", "🩹 Ezzalzouli out", "🛡️ 0.27 goals conceded per game over 15 matches", "📈 19-match unbeaten run"],
    tacticalNote: "Brazil missing 3-4 key attackers on depleted wings. Morocco's elite defensive structure under Ouahbi likely to frustrate. 88°F heat at MetLife suppresses scoring further.",
    bestBet: "Under 2.5 Goals", bestBetOdds: -120, bestBetEdge: 14.7,
    keyEdge: "Brazil's attack decimated by injuries. Morocco concede 0.27/game. 88°F heat. Perfect under storm.",
  },
  hai_sco: {
    homeFlags: ["😰 52-year WC absence", "🌍 Coach hasn't visited Haiti in 18 months (security)", "📉 No World Cup points in history"],
    awayFlags: ["🩹 Billy Gilmour (knee) out", "🌙 Night game = ideal for Scotland's physical press", "📈 4-1 vs Curacao, 4-0 vs Bolivia in warmups", "⚽ McTominay 15 international goals"],
    tacticalNote: "Night kickoff at Gillette eliminates heat factor. Scotland in sharp form. Haiti's 52-year absence creates massive occasion pressure.",
    bestBet: "Scotland -1.5 AH", bestBetOdds: +120, bestBetEdge: 13.8,
    keyEdge: "Scotland on fire in warmups. Haiti first WC in 52 years. Night game removes heat advantage.",
  },
  usa_par: {
    homeFlags: ["🏠 SoFi Stadium LA — massive home crowd", "✅ Full 26-man squad available", "📈 Beat Paraguay 2-1 in Nov 2025 friendly", "⚽ Pulisic, Balogun, McKennie all starting"],
    awayFlags: ["🩹 Julio Enciso (meniscus) doubtful", "😰 16-year WC absence", "📉 4th-lowest xG in CONMEBOL qualifying", "👴 Backline avg age 32+"],
    tacticalNote: "USA fully fit at home. Paraguay's Alfaro sets deep defensive block but their attack is severely limited. Enciso's absence removes their only creative spark. USA should control but Paraguay will make it hard.",
    bestBet: "USA Win", bestBetOdds: +105, bestBetEdge: 16.8,
    keyEdge: "USA +105 is massive value — model says 57% win probability. Market treating this as coin flip.",
  },
  aus_tur: {
    homeFlags: ["⚽ Mathew Leckie fit", "📈 Strong Asian Cup form", "🌙 Late night kickoff Vancouver"],
    awayFlags: ["⚽ Hakan Çalhanoğlu pulling strings in midfield", "📈 Strong EURO 2024 — QF", "✈️ Travel fatigue from Europe"],
    tacticalNote: "Türkiye the stronger side on paper but Australia competitive and physical. Çalhanoğlu vs Australia's press is the key duel.",
    bestBet: "Türkiye Win", bestBetOdds: -130, bestBetEdge: 7.4,
    keyEdge: "Türkiye significantly better quality. Australia tend to fade in second halves against top opposition.",
  },
  ger_cur: {
    homeFlags: ["⚽ Florian Wirtz, Musiala, Gnabry — elite attack", "📈 4-1 vs Switzerland in warmup", "🛡️ Neuer marshaling elite defense"],
    awayFlags: ["😰 First WC ever", "📉 Gave up 14 goals in CONCACAF qualifying", "🔰 Semi-professional squad"],
    tacticalNote: "Complete mismatch. Germany's attack is among the best in the tournament. Curaçao have never played at this level.",
    bestBet: "Germany -3.5 AH", bestBetOdds: -110, bestBetEdge: 18.2,
    keyEdge: "Germany score 2.4 xG per game vs opposition that conceded 14 in qualifying. Blowout likely.",
  },
  civ_ecu: {
    homeFlags: ["⚽ Sébastien Haller fit after cancer comeback", "📈 AFCON 2023 champions", "⚡ Franck Kessié physical midfield"],
    awayFlags: ["📈 8W-8D-2L in CONMEBOL qualifying — best defensive record", "⚽ Enner Valencia still leading line", "🛡️ 5 goals conceded in 18 qualifying games"],
    tacticalNote: "Ecuador's defensive discipline vs Ivory Coast's pace on the wings. Ecuador's xG conceded rate is exceptional — this is a tighter game than it looks.",
    bestBet: "Under 2.5 Goals", bestBetOdds: -115, bestBetEdge: 12.1,
    keyEdge: "Ecuador conceded only 5 in 18 qualifiers. Ivory Coast rely on transitions. Low-scoring likely.",
  },
  ned_jpn: {
    homeFlags: ["⚽ Virgil van Dijk anchoring defense", "⚽ Xavi Simons, Gakpo in attack", "📈 Strong EURO 2024 run"],
    awayFlags: ["⚽ Takumi Minamino, Ritsu Doan in form", "📈 Won Asian qualifiers unbeaten", "🧠 Moriyasu's tactical discipline"],
    tacticalNote: "Japan pulled off 2022 shock win over Germany. Will look to sit deep and counter. Netherlands have quality but Japan are organized and dangerous on the break.",
    bestBet: "Netherlands Win & Under 3.5", bestBetOdds: -115, bestBetEdge: 9.3,
    keyEdge: "Netherlands quality wins out but Japan's defensive shape keeps it tight. Narrow Dutch win most likely.",
  },
  swe_tun: {
    homeFlags: ["⚽ Alexander Isak (Newcastle) in career-best form", "📈 Won last 5 internationals", "🛡️ Solid defensive unit"],
    awayFlags: ["📉 Lost 3 of last 4", "🩹 Wahbi Khazri fitness doubt", "😰 Struggled vs European opposition historically"],
    tacticalNote: "Sweden significantly stronger. Isak vs Tunisia's CB pairing is the key duel — Sweden's pace should cause problems.",
    bestBet: "Sweden Win", bestBetOdds: -175, bestBetEdge: 8.9,
    keyEdge: "Isak in elite form. Tunisia lost 3 of last 4. Sweden should win comfortably.",
  },
  bel_egy: {
    homeFlags: ["⚽ Kevin De Bruyne fit — final WC campaign", "⚽ Romelu Lukaku starting", "📈 Strong team chemistry under new coach"],
    awayFlags: ["⚽ Mo Salah fit and motivated", "📈 AFCON runners-up 2023", "🛡️ Organized defensively"],
    tacticalNote: "Belgium's golden generation fading but still quality. De Bruyne's final WC. Egypt's Salah is a genuine match-winner and will be highly motivated.",
    bestBet: "Belgium Win", bestBetOdds: -145, bestBetEdge: 7.8,
    keyEdge: "Belgium's squad depth too much for Egypt. De Bruyne vs Salah is the storyline but Belgium should win.",
  },
  ira_nzl: {
    homeFlags: ["🛡️ Organized defensive block", "📈 Qualified comfortably through AFC", "🏠 Large Iranian diaspora crowd LA"],
    awayFlags: ["😰 First WC since 2010", "📉 Limited quality outside OFC", "🩹 Several starters below match fitness"],
    tacticalNote: "Iran should control this. New Zealand's OFC quality is significantly below AFC/UEFA standards at this level.",
    bestBet: "Iran Win", bestBetOdds: -140, bestBetEdge: 9.2,
    keyEdge: "Iran significantly better quality. New Zealand's path through OFC doesn't prepare them for this level.",
  },
  esp_cpv: {
    homeFlags: ["⚽ Pedri, Yamal, Morata — elite attack", "📈 EURO 2024 champions — peak form", "🛡️ Elite possession system"],
    awayFlags: ["😰 First WC ever", "📉 AFC limited qualifying opposition", "🔰 No players from top 5 European leagues"],
    tacticalNote: "Spain are one of the favorites. Cape Verde's first World Cup — complete mismatch in quality.",
    bestBet: "Spain -2.5 AH", bestBetOdds: -120, bestBetEdge: 17.4,
    keyEdge: "EURO 2024 champions vs first-time WC team. Spain average 2.15 xG. Cape Verde's ceiling is parking the bus.",
  },
  ksa_uru: {
    homeFlags: ["🏠 Large Middle Eastern crowd Miami", "⚽ Salem Al-Dawsari fit", "😰 2022 WC shock vs Argentina fading memory"],
    awayFlags: ["⚽ Darwin Núñez fit and in form", "📈 Strong CONMEBOL qualifying — 4th place", "🛡️ Rochet solid in goal"],
    tacticalNote: "Uruguay the stronger team with Darwin Núñez and Rodrigo Bentancur. Saudi Arabia will try to repeat their 2022 shock but Uruguay's quality is higher.",
    bestBet: "Uruguay Win", bestBetOdds: -150, bestBetEdge: 8.6,
    keyEdge: "Darwin Núñez in form. Uruguay's CONMEBOL pedigree vs Saudi Arabia's inconsistency.",
  },
  fra_sen: {
    homeFlags: ["⚽ Mbappé, Griezmann, Dembélé — frightening attack", "📈 WC favorites by many metrics", "🛡️ Camavinga, Tchouameni elite midfield"],
    awayFlags: ["⚽ Sadio Mané fit", "📈 AFCON 2022 champions", "🛡️ Organized Aliou Cissé system"],
    tacticalNote: "France are genuine favorites for the tournament. Senegal are quality — Mané motivated — but France's depth is unmatched. Mbappé vs Senegal's backline is the key duel.",
    bestBet: "France Win", bestBetOdds: -200, bestBetEdge: 9.1,
    keyEdge: "France too deep. Mbappé, Griezmann, Dembélé vs Senegal's defense is a brutal matchup for Cissé.",
  },
  irq_nor: {
    homeFlags: ["🏠 Vocal Middle Eastern crowd Boston", "🛡️ Physical defensive style"],
    awayFlags: ["⚽ Erling Haaland — tournament favorite for Golden Boot", "📈 Qualified comfortably through Europe", "⚽ Martin Ødegaard fit"],
    tacticalNote: "Norway have Haaland — enough said. Iraq will sit deep and hope. But Haaland's movement and finishing creates chances from anywhere.",
    bestBet: "Norway Win & Haaland Scores", bestBetOdds: +110, bestBetEdge: 14.3,
    keyEdge: "Haaland vs Iraq defense is as lopsided as it gets. Norway should win comfortably with Haaland scoring.",
  },
  arg_alg: {
    homeFlags: ["⚽ Messi final WC defense — massive motivation", "📈 WC holders — 36 match unbeaten run", "⚽ Martinez, Di María, Mac Allister — elite squad"],
    awayFlags: ["😰 First WC since 2014", "📉 Struggled in AFCAN qualifying", "🩹 Riyad Mahrez fitness concern"],
    tacticalNote: "Messi's final World Cup defense. Argentina are dominant. Algeria will be inspired but the quality gap is too large.",
    bestBet: "Argentina -1.5 AH", bestBetOdds: -130, bestBetEdge: 13.6,
    keyEdge: "Messi defending WC title. Argentina 36-game unbeaten run. Algeria a significant step down in quality.",
  },
  aut_jor: {
    homeFlags: ["⚽ Marcel Sabitzer in form", "📈 Strong EURO 2024 — QF", "🛡️ Organized under Rangnick"],
    awayFlags: ["😰 First WC since 1986", "📉 AFC qualifying — weaker pool", "🩹 Limited European-based players"],
    tacticalNote: "Austria significantly better. Rangnick's press system vs Jordan's limited quality. Should be comfortable.",
    bestBet: "Austria Win", bestBetOdds: -250, bestBetEdge: 7.1,
    keyEdge: "Austria EURO 2024 QF. Jordan first WC in 40 years. Quality gap is substantial.",
  },
  por_alb: {
    homeFlags: ["⚽ Ronaldo motivated — likely final WC", "⚽ Bernardo Silva, Rafael Leão, Vitinha elite squad depth", "📈 Unbeaten in UEFA qualifying"],
    awayFlags: ["😰 First ever WC appearance", "🔰 Mostly domestic Albanian league players", "📉 Conceded 2+ in 6 of last 8"],
    tacticalNote: "Portugal have the most talented squad in the tournament arguably. Ronaldo's swan song. Albania first ever WC — massive occasion penalty.",
    bestBet: "Portugal -2.5 AH", bestBetOdds: -115, bestBetEdge: 15.2,
    keyEdge: "Albania's first ever WC vs Portugal's elite squad. Ronaldo motivated for final tournament. Big win likely.",
  },
  eng_tun2: {
    homeFlags: ["⚽ Jude Bellingham in career-best form", "⚽ Harry Kane, Saka, Foden", "📈 EURO 2024 runners-up"],
    awayFlags: ["📉 Lost 3 of last 5", "🩹 Wahbi Khazri fitness doubt", "😰 Struggled vs European opposition"],
    tacticalNote: "England have elite quality with Bellingham pulling strings. Tunisia will defend deep. England should break them down.",
    bestBet: "England Win", bestBetOdds: -275, bestBetEdge: 8.4,
    keyEdge: "Bellingham, Kane, Saka vs Tunisia's defense. England EURO 2024 runners-up. Should be comfortable.",
  },
};

// Per-team scouting profiles used in detail pages
export const TEAM_PROFILES = {
  "USA":          { flag: "🇺🇸", rank: 11, style: "High press, 4-2-3-1", keyPlayer: "Christian Pulisic", recentForm: "W-W-D-W-W" },
  "Paraguay":     { flag: "🇵🇾", rank: 43, style: "Deep block, 4-4-2", keyPlayer: "Miguel Almirón", recentForm: "L-W-D-L-W" },
  "Brazil":       { flag: "🇧🇷", rank: 5,  style: "4-2-3-1, possession", keyPlayer: "Rodrygo (out)", recentForm: "W-D-W-L-W" },
  "Morocco":      { flag: "🇲🇦", rank: 14, style: "4-3-3 defensive", keyPlayer: "Hakim Ziyech", recentForm: "W-W-D-W-W" },
  "France":       { flag: "🇫🇷", rank: 2,  style: "4-3-3, counter", keyPlayer: "Kylian Mbappé", recentForm: "W-W-W-D-W" },
  "Germany":      { flag: "🇩🇪", rank: 6,  style: "4-2-3-1, press", keyPlayer: "Florian Wirtz", recentForm: "W-W-D-W-W" },
  "Spain":        { flag: "🇪🇸", rank: 1,  style: "4-3-3, tiki-taka", keyPlayer: "Lamine Yamal", recentForm: "W-W-W-W-D" },
  "Argentina":    { flag: "🇦🇷", rank: 1,  style: "4-3-3, possession", keyPlayer: "Lionel Messi", recentForm: "W-W-W-D-W" },
  "England":      { flag: "󠁧󠁢󠁥󠁮󠁧󠁿🏴", rank: 4,  style: "4-2-3-1, direct", keyPlayer: "Jude Bellingham", recentForm: "W-D-W-W-D" },
  "Portugal":     { flag: "🇵🇹", rank: 6,  style: "4-3-3, attacking", keyPlayer: "Cristiano Ronaldo", recentForm: "W-W-W-D-W" },
  "Netherlands":  { flag: "🇳🇱", rank: 8,  style: "4-3-3, press", keyPlayer: "Virgil van Dijk", recentForm: "W-W-D-W-W" },
  "Belgium":      { flag: "🇧🇪", rank: 3,  style: "3-4-3, counter", keyPlayer: "Kevin De Bruyne", recentForm: "W-W-D-W-L" },
  "Norway":       { flag: "🇳🇴", rank: 19, style: "4-3-3, direct", keyPlayer: "Erling Haaland", recentForm: "W-W-W-D-W" },
  "Mexico":       { flag: "🇲🇽", rank: 16, style: "4-3-3, counter", keyPlayer: "Hirving Lozano", recentForm: "W-W-D-W-W" },
  "Switzerland":  { flag: "🇨🇭", rank: 13, style: "4-2-3-1, solid", keyPlayer: "Granit Xhaka", recentForm: "W-D-W-W-D" },
  "Qatar":        { flag: "🇶🇦", rank: 58, style: "4-4-2, defensive", keyPlayer: "Akram Afif", recentForm: "L-L-D-L-L" },
  "Scotland":     { flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", rank: 31, style: "4-3-3, press", keyPlayer: "Andy Robertson", recentForm: "W-W-D-W-W" },
  "Haiti":        { flag: "🇭🇹", rank: 62, style: "4-4-2, physical", keyPlayer: "Duckens Nazon", recentForm: "L-D-L-W-D" },
  "Australia":    { flag: "🇦🇺", rank: 24, style: "4-3-3, counter", keyPlayer: "Mathew Leckie", recentForm: "W-D-L-W-D" },
  "Türkiye":      { flag: "🇹🇷", rank: 29, style: "4-2-3-1, press", keyPlayer: "Hakan Çalhanoğlu", recentForm: "W-W-D-W-L" },
  "Sweden":       { flag: "🇸🇪", rank: 25, style: "4-4-2, direct", keyPlayer: "Alexander Isak", recentForm: "W-W-W-D-W" },
  "Tunisia":      { flag: "🇹🇳", rank: 30, style: "4-3-3, defensive", keyPlayer: "Wahbi Khazri", recentForm: "L-D-L-D-L" },
  "Japan":        { flag: "🇯🇵", rank: 18, style: "4-2-3-1, press", keyPlayer: "Takumi Minamino", recentForm: "W-W-D-W-D" },
  "Uruguay":      { flag: "🇺🇾", rank: 15, style: "4-4-2, physical", keyPlayer: "Darwin Núñez", recentForm: "W-W-D-W-W" },
  "Senegal":      { flag: "🇸🇳", rank: 20, style: "4-3-3, physical", keyPlayer: "Sadio Mané", recentForm: "W-W-D-W-D" },
  "Ecuador":      { flag: "🇪🇨", rank: 35, style: "4-4-2, defensive", keyPlayer: "Enner Valencia", recentForm: "D-D-W-D-W" },
  "Ivory Coast":  { flag: "🇨🇮", rank: 17, style: "4-3-3, counter", keyPlayer: "Sébastien Haller", recentForm: "W-D-W-W-D" },
  "Iran":         { flag: "🇮🇷", rank: 22, style: "4-4-2, defensive", keyPlayer: "Sardar Azmoun", recentForm: "W-W-D-W-D" },
  "Egypt":        { flag: "🇪🇬", rank: 33, style: "4-2-3-1, counter", keyPlayer: "Mohamed Salah", recentForm: "W-D-W-D-W" },
  "South Korea":  { flag: "🇰🇷", rank: 23, style: "4-2-3-1, press", keyPlayer: "Son Heung-min", recentForm: "W-W-D-W-W" },
  "Algeria":      { flag: "🇩🇿", rank: 36, style: "4-3-3, counter", keyPlayer: "Riyad Mahrez", recentForm: "W-D-W-D-L" },
  "Austria":      { flag: "🇦🇹", rank: 27, style: "4-3-3, press", keyPlayer: "Marcel Sabitzer", recentForm: "W-W-D-W-D" },
  "Saudi Arabia": { flag: "🇸🇦", rank: 56, style: "4-3-3, counter", keyPlayer: "Salem Al-Dawsari", recentForm: "W-D-L-W-D" },
  "South Africa": { flag: "🇿🇦", rank: 64, style: "4-4-2, physical", keyPlayer: "Percy Tau", recentForm: "L-D-L-L-D" },
  "Czechia":      { flag: "🇨🇿", rank: 37, style: "4-2-3-1, direct", keyPlayer: "Patrik Schick", recentForm: "W-D-W-L-D" },
  "Canada":       { flag: "🇨🇦", rank: 40, style: "4-3-3, counter", keyPlayer: "Alphonso Davies", recentForm: "W-W-D-W-W" },
  "Bosnia":       { flag: "🇧🇦", rank: 45, style: "4-4-2, physical", keyPlayer: "Edin Džeko", recentForm: "W-D-L-W-D" },
  "New Zealand":  { flag: "🇳🇿", rank: 91, style: "4-4-2, physical", keyPlayer: "Chris Wood", recentForm: "W-D-L-D-W" },
  "Cape Verde":   { flag: "🇨🇻", rank: 72, style: "4-3-3, counter", keyPlayer: "Ryan Mendes", recentForm: "W-D-W-D-L" },
  "Albania":      { flag: "🇦🇱", rank: 55, style: "5-4-1, defensive", keyPlayer: "Armando Broja", recentForm: "D-L-W-D-L" },
  "China":        { flag: "🇨🇳", rank: 88, style: "4-4-2, physical", keyPlayer: "Wu Lei", recentForm: "D-L-D-W-L" },
  "Uganda":       { flag: "🇺🇬", rank: 79, style: "4-3-3, physical", keyPlayer: "Patrick Kaddu", recentForm: "W-D-L-W-D" },
  "Ghana":        { flag: "🇬🇭", rank: 60, style: "4-3-3, counter", keyPlayer: "Jordan Ayew", recentForm: "W-D-L-W-D" },
  "Panama":       { flag: "🇵🇦", rank: 70, style: "5-4-1, defensive", keyPlayer: "Rolando Blackburn", recentForm: "D-L-W-D-L" },
  "Iraq":         { flag: "🇮🇶", rank: 68, style: "4-4-2, physical", keyPlayer: "Mohanad Ali", recentForm: "W-D-W-D-L" },
  "Norway":       { flag: "🇳🇴", rank: 19, style: "4-3-3, direct", keyPlayer: "Erling Haaland", recentForm: "W-W-W-D-W" },
  "Jordan":       { flag: "🇯🇴", rank: 74, style: "4-4-2, defensive", keyPlayer: "Musa Al-Tamari", recentForm: "D-W-L-D-W" },
  "Curaçao":      { flag: "🇨🇼", rank: 110, style: "4-4-2, physical", keyPlayer: "Leandro Bacuna", recentForm: "L-L-D-L-L" },
  "Portugal":     { flag: "🇵🇹", rank: 6,  style: "4-3-3, attacking", keyPlayer: "Cristiano Ronaldo", recentForm: "W-W-W-D-W" },
};
